<?php

namespace App\Jobs;

use App\Models\Jadwal;
use App\Models\Karyawan;
use App\Models\Libur;
use Carbon\Carbon;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Illuminate\Support\Facades\Log;

class GenerateMonthlyJadwal implements ShouldQueue
{
    use Queueable;

    protected ?int $month;
    protected ?int $year;

    /**
     * Create a new job instance.
     *
     * @param int|null $month - Bulan target (default: bulan ini)
     * @param int|null $year - Tahun target (default: tahun ini)
     */
    public function __construct(?int $month = null, ?int $year = null)
    {
        $this->month = $month ?? now()->month;
        $this->year = $year ?? now()->year;
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        Log::info("=== GenerateMonthlyJadwal START ===");
        Log::info("Generating jadwal for {$this->month}/{$this->year}");

        // Get semua karyawan yang is_shift_normal = true dan active
        $karyawans = Karyawan::where('is_shift_normal', true)
            ->where('employment_status', 'active')
            ->whereNotNull('default_shift_id')
            ->get();

        if ($karyawans->isEmpty()) {
            Log::info("No karyawan with is_shift_normal = true found");
            return;
        }

        Log::info("Found {$karyawans->count()} karyawan with normal shift");

        // Get hari libur untuk bulan ini
        $liburs = Libur::where('is_active', true)
            ->whereYear('date', $this->year)
            ->whereMonth('date', $this->month)
            ->pluck('date')
            ->map(fn($date) => Carbon::parse($date)->format('Y-m-d'))
            ->toArray();

        Log::info("Found " . count($liburs) . " holidays this month");

        // Generate dates untuk bulan ini (Senin-Sabtu, exclude Minggu dan hari libur)
        $startDate = Carbon::create($this->year, $this->month, 1);
        $endDate = $startDate->copy()->endOfMonth();

        $workDates = [];
        $currentDate = $startDate->copy();

        while ($currentDate <= $endDate) {
            // Skip Minggu (dayOfWeek = 0)
            if ($currentDate->dayOfWeek !== Carbon::SUNDAY) {
                $dateString = $currentDate->format('Y-m-d');

                // Skip hari libur
                if (!in_array($dateString, $liburs)) {
                    $workDates[] = $dateString;
                }
            }
            $currentDate->addDay();
        }

        Log::info("Work dates generated: " . count($workDates) . " days");

        $createdCount = 0;
        $skippedCount = 0;

        foreach ($karyawans as $karyawan) {
            foreach ($workDates as $date) {
                // Check apakah jadwal sudah ada (baik normal maupun oncall)
                $existingJadwal = Jadwal::where('karyawan_id', $karyawan->karyawan_id)
                    ->where('date', $date)
                    ->where(function ($query) {
                        $query->whereNull('type')
                            ->orWhere('type', '!=', 'oncall');
                    })
                    ->exists();

                if ($existingJadwal) {
                    $skippedCount++;
                    continue;
                }

                // Create jadwal
                try {
                    Jadwal::create([
                        'jadwal_id' => Jadwal::generateJadwalId(),
                        'karyawan_id' => $karyawan->karyawan_id,
                        'shift_id' => $karyawan->default_shift_id,
                        'date' => $date,
                        'type' => 'normal',
                        'is_active' => true,
                        'notes' => 'Auto-generated by system',
                        'created_by_user_id' => null, // System generated
                    ]);

                    $createdCount++;
                } catch (\Exception $e) {
                    Log::error("Failed to create jadwal for {$karyawan->karyawan_id} on {$date}: " . $e->getMessage());
                }
            }
        }

        Log::info("=== GenerateMonthlyJadwal COMPLETE ===");
        Log::info("Created: {$createdCount} jadwal, Skipped: {$skippedCount}");
    }
}
